export const CategoriesList = [
  { id: 1, name: 'All', image: require('../assets/images/kids.png') },
  { id: 2, name: 'Clothing', image: require('../assets/images/kids.png') },
  {
    id: 3,
    name: 'Electronics',
    image: require('../assets/images/kids.png'),
  },
  {
    id: 4,
    name: 'Furniture',
    image: require('../assets/images/kids.png'),
  },
  { id: 5, name: 'Toys', image: require('../assets/images/beauty.png') },
  { id: 6, name: 'Books', image: require('../assets/images/womens.png') },
  { id: 7, name: 'Sports', image: require('../assets/images/mens.png') },
  { id: 8, name: 'Health', image: require('../assets/images/kids.png') },
  { id: 9, name: 'Beauty', image: require('../assets/images/kids.png') },
  { id: 10, name: 'Home', image: require('../assets/images/kids.png') },
  { id: 11, name: 'Garden', image: require('../assets/images/kids.png') },
  { id: 12, name: 'Kitchen', image: require('../assets/images/kids.png') },
  { id: 13, name: 'Office', image: require('../assets/images/kids.png') },
  { id: 14, name: 'Jewelry', image: require('../assets/images/kids.png') },
  { id: 15, name: 'Shoes', image: require('../assets/images/kids.png') },
  { id: 16, name: 'Bags', image: require('../assets/images/kids.png') },
  {
    id: 17,
    name: 'Accessories',
    image: require('../assets/images/kids.png'),
  },
  { id: 18, name: 'Gifts', image: require('../assets/images/kids.png') },
];
