export const currencyList = [
  {
    code: 'USD',
    name: 'United States Dollar',
    icon: 'dollar-sign',
    iconLibrary: 'FontAwesome5',
  },
  {
    code: 'INR',
    name: 'Indian Rupee',
    icon: 'currency-inr',
    iconLibrary: 'MaterialCommunityIcons',
  },
  { code: 'EUR', name: 'Euro', icon: 'euro-sign', iconLibrary: 'FontAwesome5' },
  {
    code: 'GBP',
    name: 'British Pound',
    icon: 'pound-sign',
    iconLibrary: 'FontAwesome5',
  },
  {
    code: 'JPY',
    name: 'Japanese Yen',
    icon: 'yen-sign',
    iconLibrary: 'FontAwesome5',
  },
  {
    code: 'AUD',
    name: 'Australian Dollar',
    icon: 'currency-usd',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'CAD',
    name: 'Canadian Dollar',
    icon: 'currency-usd',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'CHF',
    name: 'Swiss Franc',
    icon: 'currency-chf',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'CNY',
    name: 'Chinese Yuan',
    icon: 'currency-cny',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'SEK',
    name: 'Swedish Krona',
    icon: 'currency-sek',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'NZD',
    name: 'New Zealand Dollar',
    icon: 'currency-nzd',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'SGD',
    name: 'Singapore Dollar',
    icon: 'currency-sgd',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'HKD',
    name: 'Hong Kong Dollar',
    icon: 'currency-hkd',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'NOK',
    name: 'Norwegian Krone',
    icon: 'currency-nok',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'KRW',
    name: 'South Korean Won',
    icon: 'currency-krw',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'TRY',
    name: 'Turkish Lira',
    icon: 'currency-try',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'RUB',
    name: 'Russian Ruble',
    icon: 'currency-rub',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'ZAR',
    name: 'South African Rand',
    icon: 'currency-zar',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'BRL',
    name: 'Brazilian Real',
    icon: 'currency-brl',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'MXN',
    name: 'Mexican Peso',
    icon: 'currency-mxn',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'DKK',
    name: 'Danish Krone',
    icon: 'currency-dkk',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'PLN',
    name: 'Polish Zloty',
    icon: 'currency-pln',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'THB',
    name: 'Thai Baht',
    icon: 'currency-thb',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'MYR',
    name: 'Malaysian Ringgit',
    icon: 'currency-myr',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'IDR',
    name: 'Indonesian Rupiah',
    icon: 'currency-idr',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'PHP',
    name: 'Philippine Peso',
    icon: 'currency-php',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'CZK',
    name: 'Czech Koruna',
    icon: 'currency-czk',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'HUF',
    name: 'Hungarian Forint',
    icon: 'currency-huf',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'ILS',
    name: 'Israeli Shekel',
    icon: 'currency-ils',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'AED',
    name: 'UAE Dirham',
    icon: 'currency-aed',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'SAR',
    name: 'Saudi Riyal',
    icon: 'currency-sar',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'QAR',
    name: 'Qatari Riyal',
    icon: 'currency-qar',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'EGP',
    name: 'Egyptian Pound',
    icon: 'currency-egp',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'NGN',
    name: 'Nigerian Naira',
    icon: 'currency-ngn',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'BDT',
    name: 'Bangladeshi Taka',
    icon: 'currency-bdt',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'PKR',
    name: 'Pakistani Rupee',
    icon: 'currency-pkr',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'LKR',
    name: 'Sri Lankan Rupee',
    icon: 'currency-lkr',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'KWD',
    name: 'Kuwaiti Dinar',
    icon: 'currency-kwd',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'BHD',
    name: 'Bahraini Dinar',
    icon: 'currency-bhd',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'OMR',
    name: 'Omani Rial',
    icon: 'currency-omr',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'MAD',
    name: 'Moroccan Dirham',
    icon: 'currency-mad',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'JOD',
    name: 'Jordanian Dinar',
    icon: 'currency-jod',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'VND',
    name: 'Vietnamese Dong',
    icon: 'currency-vnd',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'ARS',
    name: 'Argentine Peso',
    icon: 'currency-ars',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'CLP',
    name: 'Chilean Peso',
    icon: 'currency-clp',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'COP',
    name: 'Colombian Peso',
    icon: 'currency-cop',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'UAH',
    name: 'Ukrainian Hryvnia',
    icon: 'currency-uah',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'ISK',
    name: 'Icelandic Krona',
    icon: 'currency-isk',
    iconLibrary: 'MaterialCommunityIcons',
  },
  {
    code: 'KES',
    name: 'Kenyan Shilling',
    icon: 'currency-kes',
    iconLibrary: 'MaterialCommunityIcons',
  },
];
